### ISSUE TITLE
Ignore .DS_Store files

### ISSUE THREAD

**Issue by stevearoonie** [sdd/serverless-apig-s3#7]
.DS_Store files in the client distribution will cause the deploy to fail with:
```
Serverless Error ---------------------------------------

     Expected params.ContentType to be a string
```

It would be great if these could be ignored as I don't believe we have control over when or where OSX creates them.

**Comment by sdd** [comment]
Fixed by https://github.com/sdd/serverless-apig-s3/pull/10.
